export const FETCH_POPULAR_DRINKS = "FETCH_POPULAR_DRINKS";
export const FETCH_POPULAR_DRINKS_SUCCESS = "FETCH_POPULAR_DRINKS_SUCCESS";
export const FETCH_POPULAR_DRINKS_ERROR = "FETCH_POPULAR_DRINKS_ERROR";

export const FETCH_CUSTOM_DRINKS = "FETCH_CUSTOM_DRINKS";
export const FETCH_CUSTOM_DRINKS_SUCCESS = "FETCH_CUSTOM_DRINKS_SUCCESS";
export const FETCH_CUSTOM_DRINKS_ERROR = "FETCH_CUSTOM_DRINKS_ERROR";

export const FETCH_COCKTAIL = "FETCH_COCKTAIL";
export const FETCH_COCKTAIL_SUCCESS = "FETCH_COCKTAIL_SUCCESS";
export const FETCH_COCKTAIL_ERROR = "FETCH_COCKTAIL_ERROR";

export const FETCH_RANDOM_DRINKS = "FETCH_RANDOM_DRINKS";
export const FETCH_RANDOM_DRINKS_SUCCESS = "FETCH_RANDOM_DRINKS_SUCCESS";
export const FETCH_RANDOM_DRINKS_ERROR = "FETCH_RANDOM_DRINKS_ERROR";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR";

export const CREATE_COCKTAIL = "CREATE_COCKTAIL";
export const CREATE_COCKTAIL_SUCCESS = "CREATE_COCKTAIL_SUCCESS";
export const CREATE_COCKTAIL_ERROR = "CREATE_COCKTAIL_ERROR";
